[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inference>=0.52.1",
    "opencv-python==4.10.0.84",
    "ultralytics>=8.3.186",
]
